# This is a basic workflow to help you get started with Actions

name: download-artifact

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        platform: [arm64]
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set env.HOME to $HOME
        run: echo "HOME=$HOME" >> $GITHUB_ENV
        shell: bash

      #- name: Creating cache folder on /dev/disk/azure/resource-part1 (SSD)
      #  run: |
      #    mkdir -p $HOME/cache

      - name: Creating cache folder on /dev/disk/azure/resource-part1 (SSD)
        run: |
          sudo mkdir -p /mnt/cache
          sudo chown -R runner:docker /mnt/cache
          
      - name: Creating symlink in $HOME/cache pointing to cache on /dev/disk/azure/resource-part1
        run: ln -s /mnt/cache $HOME/

      - name: download last cache
        uses: qmwd2006/actions-download-artifact@master
        with:
          workflow: download-artifact.yml
          name: kiwibrowser-ccache-${{ matrix.platform }}.tar.gz
          path: ${{env.HOME}}/

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: cache
          files: ${{env.HOME}}/cache.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
