# This is a basic workflow to help you get started with Actions

name: download-artifact

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        platform: [arm64]
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Creating cache folder on /dev/disk/azure/resource-part1 (SSD)
        run: |
          mkdir -p $HOME/cache

      - name: download last cache
        uses: qmwd2006/actions-download-artifact
        with:
          workflow: $GITHUB_WORKFLOW
          name: kiwibrowser-ccache-${{ matrix.platform }}.tar.gz
          path: ~/
          workflow_conclusion: success，timeout

      - name: untar cache
        run: |
          ls -R $HOME
          tar -zxvf $HOME/cache.tar.gz -C $HOME/cache
          rm -rf $HOME/cache.tar.gz
          tree $HOME/cache

      - name: gen a file in cache
        run: |
          touch $HOME/cache/.gitignore
          echo hello>$HOME/cache/$(date "+%Y%m%d-%H%M%S").txt
          tree $HOME/cache/

      - name: tar cache
        run: |
          tar -zcvf $HOME/cache.tar.gz -C $HOME/cache .
          du -sh $HOME/cache.tar.gz

      - name: Uploading binary objects to cache
        uses: actions/upload-artifact@v2
        with:
          name: kiwibrowser-ccache-${{ matrix.platform }}.tar.gz
          path: ~/cache.tar.gz
          retention-days: 2
