# This is a basic workflow to help you get started with Actions

name: download-release

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        platform: [arm64]
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set env.HOME to $HOME
        run: echo "HOME=$HOME" >> $GITHUB_ENV
        shell: bash

      #- name: Creating cache folder on /dev/disk/azure/resource-part1 (SSD)
      #  run: |
      #    mkdir -p $HOME/cache

      - name: Creating cache folder on /dev/disk/azure/resource-part1 (SSD)
        run: |
          sudo mkdir -p /mnt/cache
          sudo chown -R runner:docker /mnt/cache
          
      - name: Creating symlink in $HOME/cache pointing to cache on /dev/disk/azure/resource-part1
        run: ln -s /mnt/cache $HOME/

      - name: Download Release Asset
        uses: i3h/download-release-asset@v1
        with:
          owner: qmwd2006
          repo: actions-download-artifact
          tag: ccache
          file: /cache.tar.gz.*/
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: untar cache
        run: |
          ls cache.tar.gz.*
          ls cache.tar.gz.*>/dev/null 2>&1 && { cat cache.tar.gz.* | tar -zxf - -C $HOME/cache ; }
          rm -rf cache.tar.gz.*

      - name: Calculating cache size
        run: du -csh $HOME/cache
